TGT     = problem_011
SRCS    = ${TGT}.cpp
OBJS    = $(SRCS:.cpp=.o)

#--------------------------
-include ../makefile.common

#--------------------------
INCLUDES = -I. # Set include paths here, if any

LDFLAGS =      # Set load library flags here, if any

#--------------------------
