TGT     = problem_006
SRCS    = ${TGT}.cpp
OBJS    = $(SRCS:.cpp=.o)

#--------------------------
INCLUDES = -I. # Set include paths here, if any

LDFLAGS =      # Set load library flags here, if any

#--------------------------
.PHONY: all
all: ${TGT}

#--------------------------
-include ../makefile.common
